_wandb:
    value:
        cli_version: 0.24.2
        e:
            uimr3i0ao7efyifkd0j8tx9xdj1b2pxn:
                args:
                    - --config
                    - configs/base_small.yaml
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "3776651378688"
                        used: "1860759404544"
                email: keshavtibrewal2@gmail.com
                executable: /weka/innmivfractalslurmh1/home/fractal_admin/tasmay_tibrewal/Memory/.venv/bin/python3
                git:
                    commit: db4df574f22b6b631daacf6650d375b3f41042db
                    remote: https://github.com/Tasmay-Tibrewal/Memory.git
                gpu: NVIDIA H200
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-38c28b62-bb0a-a834-03c3-ac16663e9cc0
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-aed7b6a6-dbb7-7ffa-b48d-b0a32a580da2
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-08e43d8e-4d66-c667-5461-e1e739897dd7
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-1f2ffa42-b820-eb2e-5a4e-56e4bea068ce
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-f9f643a1-67a9-9e7f-c92c-2f676ec90758
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-5279d73a-e5ae-b57f-e5a3-c5398d36582c
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-f7fd24d9-e5dd-50d7-7c57-3ac8a7af89b9
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-9ed47084-d908-16a9-1588-a73bafeb5cd3
                host: innmi1srh2-p026
                memory:
                    total: "2164015292416"
                os: Linux-6.8.0-71-generic-x86_64-with-glibc2.39
                program: /weka/innmivfractalslurmh1/home/fractal_admin/tasmay_tibrewal/Memory/scripts/train.py
                python: CPython 3.11.13
                root: /weka/innmivfractalslurmh1/home/fractal_admin/tasmay_tibrewal/Memory
                startedAt: "2026-02-12T13:48:41.901131Z"
                writerId: uimr3i0ao7efyifkd0j8tx9xdj1b2pxn
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "3":
                - 13
            "4": 3.11.13
            "5": 0.24.2
            "6": 5.1.0
            "8":
                - 2
            "12": 0.24.2
            "13": linux-x86_64
memory:
    value:
        auxiliary_loss_coefficient: 0.01
        load_balance_coefficient: 0.01
        lora_alpha: 32
        lora_dropout: 0.05
        lora_rank: 16
        lora_targets:
            - q_proj
            - v_proj
        low_rank_mode: factorized
        memory_block_variant: A
        memory_dim: null
        memory_dropout: null
        memory_gradient_checkpointing: true
        memory_init_std: 0.02
        memory_layer_indices: null
        memory_layer_k: 5
        memory_layer_n: 3
        memory_layer_placement: all
        memory_num_heads: 16
        memory_num_kv_heads: 1
        memory_quant_bits: 8
        memory_rank: 64
        memory_sharing: shared
        memory_sharing_k: 2
        normalize_shared_routed_before_mixing: true
        num_chapters: 514
        num_memory_tokens: 16448
        num_shared_chapters: 2
        projection_rank: 64
        quantize_memory: false
        routed_scaling_factor: 5
        routing_strategy_inference: rolling
        routing_strategy_train: sequence
        routing_window_size: 128
        shared_routed_norm_eps: 1e-06
        shared_routed_norm_type: rms
        token_routing_kernel_version: v2
        top_k_chapters: 8
        use_auxiliary_loss: false
        use_both_memory_and_lora: false
        use_chapters: true
        use_load_balance_loss: true
        use_lora: false
        use_low_rank_memory: false
        use_low_rank_projections: false
        use_memory_adapter: true
        use_z_loss: false
        vanilla_mode: false
        wo_init_zero: true
        z_loss_coefficient: 0.001
model:
    value:
        attention_dropout: 0
        base_model_name: null
        bos_token_id: 0
        dropout: 0
        eos_token_id: 0
        freeze_base_model: false
        hidden_activation: swiglu
        hidden_dim: 512
        initializer_range: 0.02
        intermediate_dim: 1536
        max_position_embeddings: 2048
        max_seq_len: 2048
        mlp_down_proj_init_std: 0.002
        norm_eps: 1e-05
        num_heads: 8
        num_kv_heads: 4
        num_layers: 30
        pad_token_id: 0
        rope_theta: 100000
        self_attn_wo_init_std: 0.002
        tie_embeddings: true
        tokenizer_name: HuggingFaceTB/SmolLM2-135M
        use_flash_attention: true
        use_rms_norm: true
        use_rope: true
        vocab_size: 49152
training:
    value:
        adam_beta1: 0.9
        adam_beta2: 0.95
        adam_epsilon: 1e-08
        base_model_lr: 0.0003
        batch_size: 32
        dataset_name: Tasmay-Tib/fineweb-edu-10bt-split
        dataset_split: train
        dataset_subset: null
        decay_start_ratio: 0.8
        decay_start_step: null
        distributed_strategy: ddp
        early_stopping: false
        early_stopping_patience: 5
        early_stopping_threshold: 0
        eval_split: eval
        eval_steps: 100
        fsdp_sharding_strategy: FULL_SHARD
        gradient_accumulation_steps: 16
        gradient_checkpointing: true
        log_to_wandb: true
        logging_steps: 10
        lora_lr: 0.0003
        max_grad_norm: 1
        max_length: 2048
        max_steps: 9600
        memory_lr: 0.0003
        min_lr_ratio: 0.1
        mixed_precision: bf16
        num_epochs: null
        num_gpus: 8
        optimizer: adamw
        output_dir: ./outputs/base_small
        resume_from_checkpoint: null
        save_best_model: true
        save_precision: null
        save_steps: 100
        save_total_limit: 50
        scheduler: WSD
        text_field: text
        training_mode: pretraining
        wandb_project: memory-transformer
        wandb_run_name: run-full-pretrain
        warmup_ratio: null
        warmup_steps: 250
        weight_decay: 0.1
        wsd_stable_ratio: 0
        wsd_stable_steps: null
